### ISSUE TITLE
todo features

### ISSUE THREAD

**Issue by SansPapyrus683** [BitLegion/AAARGH#1]
- [x] custom test case generator
- [x] script that outputs the correct answer
- [x] checker script
if anyone has any requests, please add them here

**Comment by ryanchou-dev** [comment]
an installer or a package via apt or pypi would be nice (completely optional though, i don't even know how to do it D:)

**Comment by SansPapyrus683** [comment]
this is a rust exe ryan

**Comment by ryanchou-dev** [comment]
oh right 🤡

**Comment by ryanchou-dev** [comment]
honestly probably most detailed/comprehensive stress-tester ive ever seen...

are you gonna add it to the usaco.guide section? :O

**Comment by SansPapyrus683** [comment]
also the _only_ stress tester tbh

**Comment by SansPapyrus683** [comment]
checker script done, gonna build it later

**Comment by SansPapyrus683** [comment]
so far everything is done
